# Generated by Django 5.1.4 on 2026-06-21 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('connector_id', models.CharField(max_length=50, unique=True)),
                ('base_url', models.URLField()),
                ('type', models.CharField(choices=[('official', 'Official'), ('aggregator', 'Aggregator')], default='official', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=20)),
                ('records_processed', models.PositiveIntegerField(default=0)),
                ('error_log', models.TextField(blank=True, default='')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_runs', to='ingestion.datasource')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
