# Generated by Django 5.1.4 on 2026-06-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=50)),
                ('url', models.URLField(max_length=500, unique=True)),
                ('content', models.TextField()),
                ('status_code', models.PositiveSmallIntegerField(default=200)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.AddField(
            model_name='ingestionrun',
            name='parser_version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
