# Generated by Django 5.1.4 on 2026-10-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_rawdocument_ingestionrun_parser_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionrun',
            name='kind',
            field=models.CharField(choices=[('ingest', 'Games ingestion'), ('enrich', 'Profile enrichment')], default='ingest', max_length=10),
        ),
        migrations.AddField(
            model_name='ingestionrun',
            name='records_failed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
