# Generated by Django 5.1.4 on 2026-06-21 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('final_score_home', models.PositiveSmallIntegerField()),
                ('final_score_away', models.PositiveSmallIntegerField()),
                ('round', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(db_index=True, max_length=50)),
                ('external_id', models.CharField(db_index=True, max_length=100)),
                ('away_team_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='teams.teamseason')),
                ('home_team_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='teams.teamseason')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='teams.season')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TeamGameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveSmallIntegerField()),
                ('rebounds_off', models.PositiveSmallIntegerField()),
                ('rebounds_def', models.PositiveSmallIntegerField()),
                ('assists', models.PositiveSmallIntegerField()),
                ('steals', models.PositiveSmallIntegerField()),
                ('blocks', models.PositiveSmallIntegerField()),
                ('turnovers', models.PositiveSmallIntegerField()),
                ('fouls', models.PositiveSmallIntegerField()),
                ('field_goals_made', models.PositiveSmallIntegerField()),
                ('field_goals_att', models.PositiveSmallIntegerField()),
                ('three_point_made', models.PositiveSmallIntegerField()),
                ('three_point_att', models.PositiveSmallIntegerField()),
                ('free_throws_made', models.PositiveSmallIntegerField()),
                ('free_throws_att', models.PositiveSmallIntegerField()),
                ('possessions', models.FloatField(default=0.0)),
                ('pace', models.FloatField(default=0.0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_stats', to='games.game')),
                ('team_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_game_stats', to='teams.teamseason')),
            ],
            options={
                'verbose_name_plural': 'team game stats',
            },
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='unique_game_external_ref'),
        ),
        migrations.AddConstraint(
            model_name='teamgamestats',
            constraint=models.UniqueConstraint(fields=('game', 'team_season'), name='unique_team_stat_per_game'),
        ),
    ]
