# Generated by Django 5.1.4 on 2026-06-21 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=2, null=True)),
                ('source', models.CharField(db_index=True, max_length=50)),
                ('external_id', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='unique_person_external_ref')],
            },
        ),
        migrations.CreateModel(
            name='PlayerGameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes_played', models.PositiveSmallIntegerField()),
                ('points', models.PositiveSmallIntegerField()),
                ('rebounds_off', models.PositiveSmallIntegerField()),
                ('rebounds_def', models.PositiveSmallIntegerField()),
                ('assists', models.PositiveSmallIntegerField()),
                ('steals', models.PositiveSmallIntegerField()),
                ('blocks', models.PositiveSmallIntegerField()),
                ('turnovers', models.PositiveSmallIntegerField()),
                ('fouls', models.PositiveSmallIntegerField()),
                ('field_goals_made', models.PositiveSmallIntegerField()),
                ('field_goals_att', models.PositiveSmallIntegerField()),
                ('three_point_made', models.PositiveSmallIntegerField()),
                ('three_point_att', models.PositiveSmallIntegerField()),
                ('free_throws_made', models.PositiveSmallIntegerField()),
                ('free_throws_att', models.PositiveSmallIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='games.game')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_stats', to='players.person')),
                ('team_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_game_stats', to='teams.teamseason')),
            ],
            options={
                'verbose_name_plural': 'player game stats',
                'constraints': [models.UniqueConstraint(fields=('game', 'person'), name='unique_player_stat_per_game')],
            },
        ),
        migrations.CreateModel(
            name='PlayerSeasonAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_played', models.PositiveSmallIntegerField(default=0)),
                ('minutes_per_game', models.FloatField(default=0.0)),
                ('points_per_game', models.FloatField(default=0.0)),
                ('rebounds_per_game', models.FloatField(default=0.0)),
                ('assists_per_game', models.FloatField(default=0.0)),
                ('per', models.FloatField(default=0.0)),
                ('ts_percent', models.FloatField(default=0.0)),
                ('usage_rate', models.FloatField(default=0.0)),
                ('efg_percent', models.FloatField(default=0.0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_aggregates', to='players.person')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_aggregates', to='teams.season')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('person', 'season'), name='unique_aggregate_per_season')],
            },
        ),
        migrations.CreateModel(
            name='RosterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jersey_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=2, null=True)),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight_kg', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_entries', to='players.person')),
                ('team_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_entries', to='teams.teamseason')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('person', 'team_season'), name='unique_player_per_team_season')],
            },
        ),
        migrations.CreateModel(
            name='StaffEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_entries', to='players.person')),
                ('team_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_entries', to='teams.teamseason')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('person', 'team_season', 'role'), name='unique_staff_role_per_team_season')],
            },
        ),
    ]
