# Generated by Django 5.1.4 on 2026-06-24 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('teams', '0002_mediaasset_team_arena_team_official_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='birth_country',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='person',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='person',
            name='dominant_hand',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AddField(
            model_name='person',
            name='height_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_for_persons', to='teams.mediaasset'),
        ),
        migrations.AddField(
            model_name='person',
            name='primary_position',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='person',
            name='weight_kg',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CareerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_label', models.CharField(max_length=20)),
                ('club_name', models.CharField(max_length=150)),
                ('league_name', models.CharField(blank=True, default='', max_length=100)),
                ('source', models.CharField(db_index=True, max_length=50)),
                ('external_id', models.CharField(db_index=True, max_length=100)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career', to='players.person')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='career_entries', to='teams.team')),
            ],
            options={
                'verbose_name_plural': 'career entries',
                'ordering': ['-season_label', 'club_name'],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='unique_career_entry_external_ref')],
            },
        ),
    ]
