# Generated by Django 5.1.4 on 2026-07-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_person_birth_city_person_birth_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerseasonaggregate',
            name='blocks_per_game',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='playerseasonaggregate',
            name='fouls_per_game',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='playerseasonaggregate',
            name='ft_percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='playerseasonaggregate',
            name='steals_per_game',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='playerseasonaggregate',
            name='three_percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='playerseasonaggregate',
            name='turnovers_per_game',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='playerseasonaggregate',
            name='two_percent',
            field=models.FloatField(default=0.0),
        ),
    ]
