# Generated by Django 5.1.4 on 2026-06-24 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('team_logo', 'Team logo'), ('player_photo', 'Player photo'), ('staff_photo', 'Staff photo')], max_length=20)),
                ('source', models.CharField(db_index=True, max_length=50)),
                ('source_url', models.URLField(max_length=500, unique=True)),
                ('file', models.FileField(blank=True, upload_to='media_assets/')),
                ('license', models.CharField(blank=True, default='', max_length=200)),
                ('attribution', models.CharField(blank=True, default='', max_length=200)),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('taken_down', models.BooleanField(default=False)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['kind', 'source_url'],
            },
        ),
        migrations.AddField(
            model_name='team',
            name='arena',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='team',
            name='official_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='primary_color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='team',
            name='secondary_color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='team',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logo_for_teams', to='teams.mediaasset'),
        ),
    ]
