# Generated by Django 5.1.4 on 2026-06-28 09:12

from django.db import migrations, models

import teams.models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_mediaasset_team_arena_team_official_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='file',
            field=models.FileField(blank=True, upload_to=teams.models._media_asset_upload_path),
        ),
    ]
