# Generated by Django 5.1.4 on 2026-10-02 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubLinkOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('separate', 'Never the same club'), ('merge', 'Always the same club')], max_length=10)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='teams.team')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='teams.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('team_a', 'team_b'), name='unique_club_link_override')],
            },
        ),
    ]
